/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ConectaBanco;
import controle.ControleCardapio;
import controle.ModeloTabela;
import java.sql.Date;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import modelo.ModeloCardapio;

/**
 *
 * @author Thiago
 */
public class FrmCardapio extends javax.swing.JFrame {
    
    ConectaBanco connCarpapio = new ConectaBanco();
    ModeloCardapio mod = new ModeloCardapio();
    ControleCardapio control = new ControleCardapio();
    /**
     * Creates new form FrmCardapio
     */
    public FrmCardapio() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        connCarpapio.conexao();
        preencherTabela("select * from cardapio order by data");
        connCarpapio.executaSQL("select * from receitas where categoria_receitas = 'Salada' order by nome_receitas");
        jComboBoxSalada1.removeAllItems();
        jComboBoxSalada2.removeAllItems();
        jComboBoxSalada3.removeAllItems();
        jComboBoxSalada4.removeAllItems();
        jComboBoxSalada5.removeAllItems();
        try {
            connCarpapio.rs.first();
                jComboBoxSalada1.addItem("");
                jComboBoxSalada2.addItem("");
                jComboBoxSalada3.addItem("");
                jComboBoxSalada4.addItem("");
                jComboBoxSalada5.addItem("");

            do {
                jComboBoxSalada1.addItem(connCarpapio.rs.getString("nome_receitas"));
                jComboBoxSalada2.addItem(connCarpapio.rs.getString("nome_receitas"));
                jComboBoxSalada3.addItem(connCarpapio.rs.getString("nome_receitas"));
                jComboBoxSalada4.addItem(connCarpapio.rs.getString("nome_receitas"));
                jComboBoxSalada5.addItem(connCarpapio.rs.getString("nome_receitas"));
            } while (connCarpapio.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher combobox Saladas!" + ex);
        }
        
        connCarpapio.executaSQL("select * from receitas where categoria_receitas = 'Prato Principal' order by nome_receitas");
        jComboBoxPrato1.removeAllItems();
        jComboBoxPrato2.removeAllItems();
        jComboBoxPrato3.removeAllItems();        
        try {
            connCarpapio.rs.first();
            jComboBoxPrato1.addItem("");
            jComboBoxPrato2.addItem("");
            jComboBoxPrato3.addItem("");                
            
            do {
                jComboBoxPrato1.addItem(connCarpapio.rs.getString("nome_receitas"));
                jComboBoxPrato2.addItem(connCarpapio.rs.getString("nome_receitas"));
                jComboBoxPrato3.addItem(connCarpapio.rs.getString("nome_receitas"));                
            } while (connCarpapio.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher combobox Prato Principal!" + ex);
        }
        
        connCarpapio.executaSQL("select * from receitas where categoria_receitas = 'Guarnição' order by nome_receitas");
        jComboBoxGuarnicao1.removeAllItems();
        jComboBoxGuarnicao2.removeAllItems();
        jComboBoxGuarnicao3.removeAllItems();        
        try {
            connCarpapio.rs.first();
            jComboBoxGuarnicao1.addItem("");
            jComboBoxGuarnicao2.addItem("");
            jComboBoxGuarnicao3.addItem(""); 
            do {
                jComboBoxGuarnicao1.addItem(connCarpapio.rs.getString("nome_receitas"));
                jComboBoxGuarnicao2.addItem(connCarpapio.rs.getString("nome_receitas"));
                jComboBoxGuarnicao3.addItem(connCarpapio.rs.getString("nome_receitas"));                
            } while (connCarpapio.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher combobox Guarnição!" + ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jDateChooserData = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jComboBoxSalada1 = new javax.swing.JComboBox<>();
        jComboBoxSalada2 = new javax.swing.JComboBox<>();
        jComboBoxSalada3 = new javax.swing.JComboBox<>();
        jComboBoxSalada4 = new javax.swing.JComboBox<>();
        jComboBoxSalada5 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jComboBoxPrato1 = new javax.swing.JComboBox<>();
        jComboBoxPrato2 = new javax.swing.JComboBox<>();
        jComboBoxPrato3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jComboBoxGuarnicao1 = new javax.swing.JComboBox<>();
        jComboBoxGuarnicao2 = new javax.swing.JComboBox<>();
        jComboBoxGuarnicao3 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCardapio = new javax.swing.JTable();
        jButtonLimpar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Cardápio");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(2000, 600));

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));

        jLabel2.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jLabel2.setText("Data:");

        jDateChooserData.setDateFormatString("dd/MM/y");
        jDateChooserData.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jLabel3.setText("Saladas:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)), "Ingrediante da Marmita", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 10), new java.awt.Color(255, 102, 0))); // NOI18N

        jComboBoxSalada1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxSalada2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxSalada3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxSalada2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSalada1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBoxSalada3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxSalada1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxSalada2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxSalada3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jComboBoxSalada4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxSalada5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jLabel4.setText("Prato Principal:");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)), "Ingrediente da Marmita", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 10), new java.awt.Color(255, 102, 0))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(255, 102, 0));

        jComboBoxPrato1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxPrato2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxPrato2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPrato1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxPrato1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxPrato2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jComboBoxPrato3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jLabel5.setText("Guarnição:");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)), "Ingrediente da Marmita", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 10), new java.awt.Color(255, 102, 0))); // NOI18N

        jComboBoxGuarnicao1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxGuarnicao2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxGuarnicao2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxGuarnicao1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxGuarnicao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxGuarnicao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jComboBoxGuarnicao3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTableCardapio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableCardapio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableCardapio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCardapioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCardapio);

        jButtonLimpar.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonSalvar.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonEditar.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setFont(new java.awt.Font("Bremen Bd BT", 0, 11)); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonSair.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooserData, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(jComboBoxPrato3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxGuarnicao3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxSalada5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBoxSalada4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButtonLimpar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonSair))))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(jDateChooserData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxPrato3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxGuarnicao3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxSalada4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxSalada5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLimpar)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonSair))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Bremen Bd BT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Cadastro do cardápio do dia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(421, 421, 421)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        connCarpapio.desconecta();
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void LimpaTela() {
    
       jDateChooserData.setDate(null);              
       jComboBoxSalada1.setSelectedIndex(0);
       jComboBoxSalada2.setSelectedIndex(0);
       jComboBoxSalada3.setSelectedIndex(0);
       jComboBoxSalada4.setSelectedIndex(0);
       jComboBoxSalada5.setSelectedIndex(0);       
       jComboBoxPrato1.setSelectedIndex(0);
       jComboBoxPrato2.setSelectedIndex(0);
       jComboBoxPrato3.setSelectedIndex(0);       
       jComboBoxGuarnicao1.setSelectedIndex(0);
       jComboBoxGuarnicao2.setSelectedIndex(0);
       jComboBoxGuarnicao3.setSelectedIndex(0); 
    }
    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
               
       LimpaTela();
       jButtonSalvar.setEnabled(true);
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        
        String data = new SimpleDateFormat("yyyy-MM-dd").format(jDateChooserData.getDate());        
        mod.setData(data);
        mod.setSalada1((String) jComboBoxSalada1.getSelectedItem());
        mod.setSalada2((String) jComboBoxSalada2.getSelectedItem());
        mod.setSalada3((String) jComboBoxSalada3.getSelectedItem());
        mod.setSalada4((String) jComboBoxSalada4.getSelectedItem());
        mod.setSalada5((String) jComboBoxSalada5.getSelectedItem());
        mod.setPrato1((String) jComboBoxPrato1.getSelectedItem());
        mod.setPrato2((String) jComboBoxPrato2.getSelectedItem());
        mod.setPrato3((String) jComboBoxPrato3.getSelectedItem());
        mod.setGuarnicao1((String) jComboBoxGuarnicao1.getSelectedItem());
        mod.setGuarnicao2((String) jComboBoxGuarnicao2.getSelectedItem());
        mod.setGuarnicao3((String) jComboBoxGuarnicao3.getSelectedItem());
        mod.setSalada_marmita1((String) jComboBoxSalada1.getSelectedItem());
        mod.setSalada_marmita2((String) jComboBoxSalada2.getSelectedItem()); 
        control.InserirCardapio(mod);
        preencherTabela("select * from cardapio order by data");
        LimpaTela();
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        
        String data = new SimpleDateFormat("yyyy-MM-dd").format(jDateChooserData.getDate());        
        mod.setData(data);
        mod.setSalada1((String) jComboBoxSalada1.getSelectedItem());
        mod.setSalada2((String) jComboBoxSalada2.getSelectedItem());
        mod.setSalada3((String) jComboBoxSalada3.getSelectedItem());
        mod.setSalada4((String) jComboBoxSalada4.getSelectedItem());
        mod.setSalada5((String) jComboBoxSalada5.getSelectedItem());
        mod.setPrato1((String) jComboBoxPrato1.getSelectedItem());
        mod.setPrato2((String) jComboBoxPrato2.getSelectedItem());
        mod.setPrato3((String) jComboBoxPrato3.getSelectedItem());
        mod.setGuarnicao1((String) jComboBoxGuarnicao1.getSelectedItem());
        mod.setGuarnicao2((String) jComboBoxGuarnicao2.getSelectedItem());
        mod.setGuarnicao3((String) jComboBoxGuarnicao3.getSelectedItem());
        mod.setSalada_marmita1((String) jComboBoxSalada1.getSelectedItem());
        mod.setSalada_marmita2((String) jComboBoxSalada2.getSelectedItem());
        control.ExcluiCardapio(mod);
        preencherTabela("select * from cardapio order by data");
        LimpaTela();
        jButtonSalvar.setEnabled(true);
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        
        String data = new SimpleDateFormat("yyyy-MM-dd").format(jDateChooserData.getDate());        
        mod.setData(data);
        mod.setSalada1((String) jComboBoxSalada1.getSelectedItem());
        mod.setSalada2((String) jComboBoxSalada2.getSelectedItem());
        mod.setSalada3((String) jComboBoxSalada3.getSelectedItem());
        mod.setSalada4((String) jComboBoxSalada4.getSelectedItem());
        mod.setSalada5((String) jComboBoxSalada5.getSelectedItem());
        mod.setPrato1((String) jComboBoxPrato1.getSelectedItem());
        mod.setPrato2((String) jComboBoxPrato2.getSelectedItem());
        mod.setPrato3((String) jComboBoxPrato3.getSelectedItem());
        mod.setGuarnicao1((String) jComboBoxGuarnicao1.getSelectedItem());
        mod.setGuarnicao2((String) jComboBoxGuarnicao2.getSelectedItem());
        mod.setGuarnicao3((String) jComboBoxGuarnicao3.getSelectedItem());
        mod.setSalada_marmita1((String) jComboBoxSalada1.getSelectedItem());
        mod.setSalada_marmita2((String) jComboBoxSalada2.getSelectedItem());
        control.AlteraCardapio(mod);
        preencherTabela("select * from cardapio order by data");
        LimpaTela();
        jButtonSalvar.setEnabled(true);
    }//GEN-LAST:event_jButtonEditarActionPerformed
    public String transforma_data(String data){

        String dia=data.split("/")[2];
        String mes=data.split("/")[1];
        String ano=data.split("/")[0];

        return dia+"-"+mes+"-"+ano;

       }    
 
    private void jTableCardapioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCardapioMouseClicked
       connCarpapio.conexao();       
       String data = ""+jTableCardapio.getValueAt(jTableCardapio.getSelectedRow(),0);
       String datafinal = transforma_data(data);
       connCarpapio.executaSQL("select * from cardapio where data='"+datafinal+"'");             
              
       try { 
            SimpleDateFormat formataData = new SimpleDateFormat("dd/MM/yyyy");
            java.util.Date dataEntrada = formataData.parse(data);                
            connCarpapio.rs.first();            
            jDateChooserData.setDate(dataEntrada);
            jComboBoxSalada1.setSelectedItem(connCarpapio.rs.getString("salada1"));
            jComboBoxSalada2.setSelectedItem(connCarpapio.rs.getString("salada2"));
            jComboBoxSalada3.setSelectedItem(connCarpapio.rs.getString("salada3"));
            jComboBoxSalada4.setSelectedItem(connCarpapio.rs.getString("salada4"));
            jComboBoxSalada5.setSelectedItem(connCarpapio.rs.getString("salada5"));
            jComboBoxPrato1.setSelectedItem(connCarpapio.rs.getString("prato1"));
            jComboBoxPrato2.setSelectedItem(connCarpapio.rs.getString("prato2"));
            jComboBoxPrato3.setSelectedItem(connCarpapio.rs.getString("prato3"));
            jComboBoxGuarnicao1.setSelectedItem(connCarpapio.rs.getString("guarnicao1"));
            jComboBoxGuarnicao2.setSelectedItem(connCarpapio.rs.getString("guarnicao2"));
            jComboBoxGuarnicao3.setSelectedItem(connCarpapio.rs.getString("guarnicao3"));  
            jButtonSalvar.setEnabled(false);
        } catch (SQLException s){
            JOptionPane.showMessageDialog(rootPane,"Erro ao selecionar os dados!\nErro: " + s);        
        } catch (ParseException ex) {
            Logger.getLogger(FrmCardapio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jTableCardapioMouseClicked

    public void preencherTabela(String SQL){
        ArrayList dados = new ArrayList();
    
        String [] Colunas = new String[]{"Data","Salada 1","Salada 2","Salada 3","Salada 4","Salada 5","Prato Principal 1","Prato Principal 2","Prato Principal 3","Guarnição 1","Guarnição 2","Guarnição 3","Salada Marmita 1","Salada Marmita 2"};
        connCarpapio.executaSQL(SQL);
        
            try {
                connCarpapio.rs.first();                      
                do{
                    Date dataFormat = connCarpapio.rs.getDate("data");
                    String data = new SimpleDateFormat("dd/MM/yyyy").format(dataFormat);
                    dados.add(new Object[]{data,connCarpapio.rs.getString("salada1"),connCarpapio.rs.getString("salada2"),connCarpapio.rs.getString("salada3"),connCarpapio.rs.getString("salada4"),connCarpapio.rs.getString("salada5"),connCarpapio.rs.getString("prato1"),connCarpapio.rs.getString("prato2"),connCarpapio.rs.getString("prato3"),connCarpapio.rs.getString("guarnicao1"),connCarpapio.rs.getString("guarnicao2"),connCarpapio.rs.getString("guarnicao3"),connCarpapio.rs.getString("salada_marmita1"),connCarpapio.rs.getString("salada_marmita2"),});
                }while(connCarpapio.rs.next());                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane,"Erro ao preencher o ArrayList!\n Erro: "+ex);
            }
                        
            ModeloTabela modelo = new ModeloTabela(dados, Colunas);
            jTableCardapio.setModel(modelo);
            jTableCardapio.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTableCardapio.getColumnModel().getColumn(0).setResizable(true);
            jTableCardapio.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTableCardapio.getColumnModel().getColumn(1).setResizable(true);
            jTableCardapio.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTableCardapio.getColumnModel().getColumn(2).setResizable(true);
            jTableCardapio.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTableCardapio.getColumnModel().getColumn(3).setResizable(true);
            jTableCardapio.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTableCardapio.getColumnModel().getColumn(4).setResizable(true);
            jTableCardapio.getColumnModel().getColumn(5).setPreferredWidth(100);
            jTableCardapio.getColumnModel().getColumn(5).setResizable(true);
            jTableCardapio.getColumnModel().getColumn(6).setPreferredWidth(100);
            jTableCardapio.getColumnModel().getColumn(6).setResizable(true);
            jTableCardapio.getColumnModel().getColumn(7).setPreferredWidth(100);
            jTableCardapio.getColumnModel().getColumn(7).setResizable(true);
            jTableCardapio.getColumnModel().getColumn(8).setPreferredWidth(100);
            jTableCardapio.getColumnModel().getColumn(8).setResizable(true);
            jTableCardapio.getColumnModel().getColumn(9).setPreferredWidth(100);
            jTableCardapio.getColumnModel().getColumn(9).setResizable(true);
            jTableCardapio.getColumnModel().getColumn(10).setPreferredWidth(100);
            jTableCardapio.getColumnModel().getColumn(10).setResizable(true);
            jTableCardapio.getColumnModel().getColumn(11).setPreferredWidth(100);
            jTableCardapio.getColumnModel().getColumn(11).setResizable(true);
            jTableCardapio.getColumnModel().getColumn(12).setPreferredWidth(100);
            jTableCardapio.getColumnModel().getColumn(12).setResizable(true);
            jTableCardapio.getColumnModel().getColumn(13).setPreferredWidth(100);
            jTableCardapio.getColumnModel().getColumn(13).setResizable(true);
            jTableCardapio.getTableHeader().setReorderingAllowed(false);
            jTableCardapio.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);            
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCardapio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxGuarnicao1;
    private javax.swing.JComboBox<String> jComboBoxGuarnicao2;
    private javax.swing.JComboBox<String> jComboBoxGuarnicao3;
    private javax.swing.JComboBox<String> jComboBoxPrato1;
    private javax.swing.JComboBox<String> jComboBoxPrato2;
    private javax.swing.JComboBox<String> jComboBoxPrato3;
    private javax.swing.JComboBox<String> jComboBoxSalada1;
    private javax.swing.JComboBox<String> jComboBoxSalada2;
    private javax.swing.JComboBox<String> jComboBoxSalada3;
    private javax.swing.JComboBox<String> jComboBoxSalada4;
    private javax.swing.JComboBox<String> jComboBoxSalada5;
    private com.toedter.calendar.JDateChooser jDateChooserData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCardapio;
    // End of variables declaration//GEN-END:variables
}
