/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import br.com.parg.viacep.ViaCEP;
import br.com.parg.viacep.ViaCEPException;
import controle.ConectaBanco;
import controle.ControleClientes;
import controle.GeraLog;
import controle.ModeloTabela;
import java.sql.SQLException;
import javax.swing.text.*;
import java.text.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import modelo.ModeloClientes;

/**
 *
 * @author Thiago
 */
public final class FrmClientes extends javax.swing.JFrame {
    
        private MaskFormatter mascaraRG;
        private MaskFormatter mascaraCPF;        
        private MaskFormatter mascaraCNPJ;
        
        ConectaBanco connClientes = new ConectaBanco();
        ModeloClientes mod = new ModeloClientes();
        ControleClientes control = new ControleClientes();
        GeraLog log = new GeraLog();
        
        
    /**
     * Creates new form FrmClientes
     */
    public FrmClientes() {
        initComponents();
        connClientes.conexao();
        jRadioButtonFisica.setSelected(true);
        jTextAreaObs.setLineWrap(true);
        preencherTabela("select * from clientes order by id_cliente");
        
        try {                
                mascaraRG = new MaskFormatter("#.###.###-#");
                mascaraCPF = new MaskFormatter( "###.###.###-##" );               
                mascaraCNPJ = new MaskFormatter( "##.###.###/####-##" );
                
        } catch (ParseException ex) { 
            log.gravaErro(ex.toString(), "FrmClientes");
        }
        jFormattedTextFieldCPFCNPJ.setFormatterFactory(new DefaultFormatterFactory( mascaraCPF ) );        
        jFormattedTextFieldRGIE.setFormatterFactory(new DefaultFormatterFactory(mascaraRG));
    }
    
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupPessoa = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelCPFCNPJ = new javax.swing.JLabel();
        jFormattedTextFieldCPFCNPJ = new javax.swing.JFormattedTextField();
        jLabelRGIE = new javax.swing.JLabel();
        jFormattedTextFieldRGIE = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEmpresa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextFieldTelefone = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldCelular = new javax.swing.JFormattedTextField();
        jRadioButtonJuridica = new javax.swing.JRadioButton();
        jRadioButtonFisica = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextFieldCEP = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldComplemento = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jComboBoxUF = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaObs = new javax.swing.JTextArea();
        jButtonSalvar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jButtonSair = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Clientes");

        jPanel1.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Bremen Bd BT", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Cadastro de Clientes");

        jLabelNome.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jLabelNome.setText("Nome:");

        jLabelCPFCNPJ.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jLabelCPFCNPJ.setText("CPF:");

        jFormattedTextFieldCPFCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));

        jLabelRGIE.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jLabelRGIE.setText("RG:");

        try {
            jFormattedTextFieldRGIE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jLabel5.setText("Empresa:");

        jLabel6.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jLabel6.setText("Email:");

        jLabel2.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jLabel2.setText("Telefone:");

        try {
            jFormattedTextFieldTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jLabel3.setText("Celular:");

        try {
            jFormattedTextFieldCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        buttonGroupPessoa.add(jRadioButtonJuridica);
        jRadioButtonJuridica.setText("Pessoa Jurídica");
        jRadioButtonJuridica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonJuridicaMouseClicked(evt);
            }
        });

        buttonGroupPessoa.add(jRadioButtonFisica);
        jRadioButtonFisica.setText("Pessoa Física");
        jRadioButtonFisica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonFisicaMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jLabel7.setText("CEP:");

        try {
            jFormattedTextFieldCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCEPActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jLabel8.setText("Endereço:");

        jLabel9.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jLabel9.setText("Número:");

        jLabel10.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jLabel10.setText("Código Cliente:");

        jTextFieldCodigo.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jLabel11.setText("Comp.:");

        jLabel12.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jLabel12.setText("Bairro:");

        jLabel13.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jLabel13.setText("Cidade:");

        jComboBoxUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UF", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        jLabel14.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jLabel14.setText("Observações:");

        jTextAreaObs.setColumns(20);
        jTextAreaObs.setRows(5);
        jScrollPane1.setViewportView(jTextAreaObs);

        jButtonSalvar.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonEditar.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonLimpar.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jTextFieldPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarKeyReleased(evt);
            }
        });

        jButtonSair.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableClientes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jFormattedTextFieldRGIE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelNome)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelCPFCNPJ)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextFieldCPFCNPJ)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelRGIE)
                                        .addGap(104, 104, 104))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioButtonFisica)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButtonJuridica)
                                        .addGap(245, 245, 245))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jFormattedTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(46, 46, 46)
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jFormattedTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel9))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldCidade)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jButtonSair))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1))
                            .addComponent(jScrollPane3))))
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonJuridica)
                    .addComponent(jRadioButtonFisica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCPFCNPJ)
                    .addComponent(jFormattedTextFieldCPFCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRGIE)
                    .addComponent(jFormattedTextFieldRGIE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jFormattedTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jFormattedTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPesquisar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonSalvar)
                        .addComponent(jButtonEditar)
                        .addComponent(jButtonExcluir)
                        .addComponent(jButtonLimpar)
                        .addComponent(jButtonSair)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(695, 606));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        connClientes.desconecta();
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    public void preencherTabela(String SQL){
        ArrayList dados = new ArrayList();
    
        String [] Colunas = new String[]{"Código","Nome","CPF/CNPJ","RG/IE","Empresa","Email","Telefone","Celular","CEP","Endereço","Número","Complemento","Bairro","Cidade","UF","Obs"};
    
        connClientes.executaSQL(SQL);
        try {
            
            if(!connClientes.rs.next()) {
                
            } else {
                    connClientes.rs.first();
                    do{
                        dados.add(new Object[]{connClientes.rs.getInt("id_cliente"),connClientes.rs.getString("nome_cliente"),connClientes.rs.getString("cpfcnpj_cliente"),connClientes.rs.getString("rgie_cliente"),connClientes.rs.getString("empresa_cliente"),connClientes.rs.getString("email_cliente"),connClientes.rs.getString("telefone_cliente"),connClientes.rs.getString("celular_cliente"),connClientes.rs.getString("cep_cliente"),connClientes.rs.getString("endereco_cliente"),connClientes.rs.getInt("numero_cliente"),connClientes.rs.getString("complemento_cliente"),connClientes.rs.getString("bairro_cliente"),connClientes.rs.getString("cidade_cliente"),connClientes.rs.getString("uf_cliente"),connClientes.rs.getString("obs_cliente")});
                    }while(connClientes.rs.next());
            }
        } catch (SQLException ex) {
              JOptionPane.showMessageDialog(rootPane,"Erro ao preencher o ArrayList!\n Erro: "+ex);
              log.gravaErro(ex.toString(), "PreencherTabela Clientes");
        }
        
        
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTableClientes.setModel(modelo);
        jTableClientes.getColumnModel().getColumn(0).setPreferredWidth(35);
        jTableClientes.getColumnModel().getColumn(0).setResizable(true);
        jTableClientes.getColumnModel().getColumn(1).setPreferredWidth(180);
        jTableClientes.getColumnModel().getColumn(1).setResizable(true);
        jTableClientes.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableClientes.getColumnModel().getColumn(2).setResizable(true);
        jTableClientes.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTableClientes.getColumnModel().getColumn(3).setResizable(true);
        jTableClientes.getColumnModel().getColumn(4).setPreferredWidth(90);
        jTableClientes.getColumnModel().getColumn(4).setResizable(true);
        jTableClientes.getColumnModel().getColumn(5).setPreferredWidth(90);
        jTableClientes.getColumnModel().getColumn(5).setResizable(true);
        jTableClientes.getColumnModel().getColumn(6).setPreferredWidth(90);
        jTableClientes.getColumnModel().getColumn(6).setResizable(true);
        jTableClientes.getColumnModel().getColumn(7).setPreferredWidth(100);
        jTableClientes.getColumnModel().getColumn(7).setResizable(true);
        jTableClientes.getColumnModel().getColumn(8).setPreferredWidth(90);
        jTableClientes.getColumnModel().getColumn(8).setResizable(true);
        jTableClientes.getColumnModel().getColumn(9).setPreferredWidth(90);
        jTableClientes.getColumnModel().getColumn(9).setResizable(true);
        jTableClientes.getColumnModel().getColumn(10).setPreferredWidth(70);
        jTableClientes.getColumnModel().getColumn(10).setResizable(true);
        jTableClientes.getColumnModel().getColumn(11).setPreferredWidth(35);
        jTableClientes.getColumnModel().getColumn(11).setResizable(true);
        jTableClientes.getColumnModel().getColumn(12).setPreferredWidth(90);
        jTableClientes.getColumnModel().getColumn(12).setResizable(true);
        jTableClientes.getColumnModel().getColumn(13).setPreferredWidth(90);
        jTableClientes.getColumnModel().getColumn(13).setResizable(true);
        jTableClientes.getColumnModel().getColumn(14).setPreferredWidth(30);
        jTableClientes.getColumnModel().getColumn(14).setResizable(true);
        jTableClientes.getColumnModel().getColumn(15).setPreferredWidth(90);
        jTableClientes.getColumnModel().getColumn(15).setResizable(true);
        jTableClientes.getTableHeader().setReorderingAllowed(false);
        jTableClientes.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);        
        
    }  
    private void LimpaTela(){
        jTextFieldCodigo.setText("");
        jTextFieldNome.setText("");
        jFormattedTextFieldCPFCNPJ.setText("");
        jFormattedTextFieldRGIE.setText("");
        jFormattedTextFieldTelefone.setText("");
        jFormattedTextFieldCelular.setText("");
        jFormattedTextFieldCEP.setText("");
        jTextAreaObs.setText("");
        jTextFieldBairro.setText("");
        jTextFieldCidade.setText("");
        jTextFieldComplemento.setText("");
        jTextFieldEmail.setText("");
        jTextFieldEmpresa.setText("");
        jTextFieldEndereco.setText("");
        jTextFieldNumero.setText("");
        jTextFieldPesquisar.setText("");
        jComboBoxUF.setSelectedIndex(0);
    
    }
    private void jRadioButtonFisicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonFisicaMouseClicked
        jLabelNome.setText("Nome:");
        jLabelCPFCNPJ.setText("CPF:");
        jLabelRGIE.setText("RG:");
        jFormattedTextFieldCPFCNPJ.setValue(null);
        jFormattedTextFieldRGIE.setValue(null);
        jFormattedTextFieldCPFCNPJ.setFormatterFactory(new DefaultFormatterFactory( mascaraCPF ) );        
        jFormattedTextFieldRGIE.setFormatterFactory(new DefaultFormatterFactory( mascaraRG ));
    }//GEN-LAST:event_jRadioButtonFisicaMouseClicked

    private void jRadioButtonJuridicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonJuridicaMouseClicked
        jLabelNome.setText("Razão:");
        jLabelCPFCNPJ.setText("CNPJ:");
        jLabelRGIE.setText("IE:");
        jFormattedTextFieldCPFCNPJ.setValue(null); 
        jFormattedTextFieldRGIE.setFormatterFactory(null);
        jFormattedTextFieldRGIE.setText("");        
        jFormattedTextFieldCPFCNPJ.setFormatterFactory(new DefaultFormatterFactory( mascaraCNPJ ) );        
    }//GEN-LAST:event_jRadioButtonJuridicaMouseClicked

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        LimpaTela();
        jButtonSalvar.setEnabled(true);        
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jFormattedTextFieldCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCEPActionPerformed
        buscaCep();
    }//GEN-LAST:event_jFormattedTextFieldCEPActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        
     String num = jTextFieldNumero.getText();     
      
      if (num.trim().equals("")){
           mod.setNumero_cliente(0);
      }  else {
          mod.setNumero_cliente(Integer.parseInt(num));
      }      
        
        mod.setNome_cliente(jTextFieldNome.getText());
        mod.setCpfcnpj_cliente(jFormattedTextFieldCPFCNPJ.getText());
        mod.setRgie_cliente(jFormattedTextFieldRGIE.getText());
        mod.setEmpresa_cliente(jTextFieldEmpresa.getText());
        mod.setEmail_cliente(jTextFieldEmail.getText());
        mod.setTelefone_cliente(jFormattedTextFieldTelefone.getText());
        mod.setCelular_cliente(jFormattedTextFieldCelular.getText());
        mod.setCep_cliente(jFormattedTextFieldCEP.getText());
        mod.setEndereco_cliente(jTextFieldEndereco.getText());        
        mod.setComplemento_cliente(jTextFieldComplemento.getText());
        mod.setBairro_cliente(jTextFieldBairro.getText());
        mod.setCidade_cliente(jTextFieldCidade.getText());
        mod.setUf_cliente((String) jComboBoxUF.getSelectedItem());
        mod.setObs_cliente(jTextAreaObs.getText());
        control.InserirClientes(mod);
        preencherTabela("select * from clientes order by id_cliente");
        LimpaTela();
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        
        mod.setId_cliente(Integer.parseInt(jTextFieldCodigo.getText()));
        mod.setNome_cliente(jTextFieldNome.getText());
        mod.setCpfcnpj_cliente(jFormattedTextFieldCPFCNPJ.getText());
        mod.setRgie_cliente(jFormattedTextFieldRGIE.getText());
        mod.setEmpresa_cliente(jTextFieldEmpresa.getText());
        mod.setEmail_cliente(jTextFieldEmail.getText());
        mod.setTelefone_cliente(jFormattedTextFieldTelefone.getText());
        mod.setCelular_cliente(jFormattedTextFieldCelular.getText());
        mod.setCep_cliente(jFormattedTextFieldCEP.getText());
        mod.setEndereco_cliente(jTextFieldEndereco.getText());
        mod.setNumero_cliente(Integer.parseInt(jTextFieldNumero.getText()));
        mod.setComplemento_cliente(jTextFieldComplemento.getText());
        mod.setBairro_cliente(jTextFieldBairro.getText());
        mod.setCidade_cliente(jTextFieldCidade.getText());
        mod.setUf_cliente((String) jComboBoxUF.getSelectedItem());
        mod.setObs_cliente(jTextAreaObs.getText());
        control.ExcluiClientes(mod);
        preencherTabela("select * from clientes order by id_cliente");
        LimpaTela();
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        
       String num = jTextFieldNumero.getText();     
      
      if (num.trim().equals("")){
           mod.setNumero_cliente(0);
      }  else {
          mod.setNumero_cliente(Integer.parseInt(num));
      }      
      
        mod.setId_cliente(Integer.parseInt(jTextFieldCodigo.getText()));
        mod.setNome_cliente(jTextFieldNome.getText());
        mod.setCpfcnpj_cliente(jFormattedTextFieldCPFCNPJ.getText());
        mod.setRgie_cliente(jFormattedTextFieldRGIE.getText());
        mod.setEmpresa_cliente(jTextFieldEmpresa.getText());
        mod.setEmail_cliente(jTextFieldEmail.getText());
        mod.setTelefone_cliente(jFormattedTextFieldTelefone.getText());
        mod.setCelular_cliente(jFormattedTextFieldCelular.getText());
        mod.setCep_cliente(jFormattedTextFieldCEP.getText());
        mod.setEndereco_cliente(jTextFieldEndereco.getText());        
        mod.setComplemento_cliente(jTextFieldComplemento.getText());
        mod.setBairro_cliente(jTextFieldBairro.getText());
        mod.setCidade_cliente(jTextFieldCidade.getText());
        mod.setUf_cliente((String) jComboBoxUF.getSelectedItem());
        mod.setObs_cliente(jTextAreaObs.getText());
        control.AlteraClientes(mod);
        preencherTabela("select * from clientes order by id_cliente");
        LimpaTela();
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jTableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientesMouseClicked
        
       connClientes.conexao();
       String cod = ""+jTableClientes.getValueAt(jTableClientes.getSelectedRow(),0);
       connClientes.executaSQL("select * from clientes where id_cliente='"+cod+"'");
        
            
       try {                     
            connClientes.rs.first();            
            
            String cont = connClientes.rs.getString("cpfcnpj_cliente");
            
            if (cont.length() == 18) {
                jRadioButtonJuridica.setSelected(true);
                jRadioButtonJuridicaMouseClicked(evt);
            } else {
                jRadioButtonFisica.setSelected(true);
                jRadioButtonFisicaMouseClicked(evt);
            }
            
            jTextFieldCodigo.setText(String.valueOf(connClientes.rs.getInt("id_cliente")));
            jTextFieldNome.setText(connClientes.rs.getString("nome_cliente"));
            jFormattedTextFieldCPFCNPJ.setText(connClientes.rs.getString("cpfcnpj_cliente"));
            jFormattedTextFieldRGIE.setText(connClientes.rs.getString("rgie_cliente"));
            jTextFieldEmpresa.setText(connClientes.rs.getString("empresa_cliente"));
            jTextFieldEmail.setText(connClientes.rs.getString("email_cliente"));       
            jFormattedTextFieldTelefone.setText(connClientes.rs.getString("telefone_cliente"));
            jFormattedTextFieldCelular.setText(connClientes.rs.getString("celular_cliente"));
            jFormattedTextFieldCEP.setText(connClientes.rs.getString("cep_cliente"));
            jTextFieldEndereco.setText(connClientes.rs.getString("endereco_cliente"));
            jTextFieldNumero.setText(String.valueOf(connClientes.rs.getInt("numero_cliente")));
            jTextFieldComplemento.setText(connClientes.rs.getString("complemento_cliente"));
            jTextFieldBairro.setText(connClientes.rs.getString("bairro_cliente"));
            jTextFieldCidade.setText(connClientes.rs.getString("cidade_cliente"));
            jComboBoxUF.setSelectedItem(connClientes.rs.getString("uf_cliente"));            
            jTextAreaObs.setText(connClientes.rs.getString("obs_cliente"));                       
            jButtonSalvar.setEnabled(false);
            
        } catch (SQLException s){
            JOptionPane.showMessageDialog(rootPane,"Erro ao selecionar os dados!\nErro: " + s); 
            log.gravaErro(s.toString(), "TableClientesMouseClicked");
        }
    }//GEN-LAST:event_jTableClientesMouseClicked

    private void jTextFieldPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarKeyReleased
        preencherTabela("select * from clientes where nome_cliente like '%" + jTextFieldPesquisar.getText() + "%' or telefone_cliente like '%" + jTextFieldPesquisar.getText() + "%' or celular_cliente like '%" + jTextFieldPesquisar.getText() + "%' or empresa_cliente like '%" + jTextFieldPesquisar.getText() + "%' or email_cliente like '%" + jTextFieldPesquisar.getText() + "%' or endereco_cliente like '%" + jTextFieldPesquisar.getText() + "%'");
    }//GEN-LAST:event_jTextFieldPesquisarKeyReleased

    public void buscaCep() {
        
        ViaCEP viaCep = new ViaCEP();
        
            try {
                viaCep.buscar(jFormattedTextFieldCEP.getText());
                jTextFieldEndereco.setText(viaCep.getLogradouro());
                jTextFieldCidade.setText(viaCep.getLocalidade());
                jTextFieldBairro.setText(viaCep.getBairro());
                jComboBoxUF.setSelectedItem(viaCep.getUf());
                jTextFieldNumero.requestFocus();
            } catch (ViaCEPException ex) {
                Logger.getLogger(FrmClientes.class.getName()).log(Level.SEVERE, null, ex);
                log.gravaErro(ex.toString(), "buscaCep");
            }
        
     /*   WebServiceCep webServiceCep = WebServiceCep.searchCep(jFormattedTextFieldCEP.getText());
        //A ferramenta de busca ignora qualquer caracter que n?o seja n?mero.

        //caso a busca ocorra bem, imprime os resultados.
        if (webServiceCep.wasSuccessful()) {
            jTextFieldEndereco.setText(webServiceCep.getLogradouroFull());
            jTextFieldCidade.setText(webServiceCep.getCidade());
            jTextFieldBairro.setText(webServiceCep.getBairro());
            jComboBoxUF.setSelectedItem(webServiceCep.getUf());
            System.out.println("Cep: " + webServiceCep.getCep());
            System.out.println("Logradouro: " + webServiceCep.getLogradouroFull());
            System.out.println("Bairro: " + webServiceCep.getBairro());
            System.out.println("Cidade: "
                    + webServiceCep.getCidade() + "/" + webServiceCep.getUf());

            //caso haja problemas imprime as exce??es.
        } else {
            JOptionPane.showMessageDialog(null, "Erro numero: " + webServiceCep.getResulCode());

            JOptionPane.showMessageDialog(null, "Descrição do erro: " + webServiceCep.getResultText());
        }
            
      */
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmClientes().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupPessoa;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxUF;
    private javax.swing.JFormattedTextField jFormattedTextFieldCEP;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPFCNPJ;
    private javax.swing.JFormattedTextField jFormattedTextFieldCelular;
    private javax.swing.JFormattedTextField jFormattedTextFieldRGIE;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCPFCNPJ;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelRGIE;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonFisica;
    private javax.swing.JRadioButton jRadioButtonJuridica;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTextArea jTextAreaObs;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldComplemento;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEmpresa;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldPesquisar;
    // End of variables declaration//GEN-END:variables
}
