/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ConectaBanco;
import controle.ControlePedido;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.NumberFormat;
import javax.swing.JOptionPane;
import modelo.ModeloPedido;

/**
 *
 * @author thiag
 */
public final class FrmFinalizacao extends javax.swing.JFrame {
    
    ConectaBanco connFinalizacao = new ConectaBanco();    
    ModeloPedido mod = new ModeloPedido();    
    ControlePedido control = new ControlePedido();    
    String caracteresNum = "0987654321";
    NumberFormat formatoMoeda = NumberFormat.getCurrencyInstance();    
    Double saldo = 0.0;

    /**
     * Creates new form FrmFinalizacao
     */
    public FrmFinalizacao() {
        initComponents();         
        LimpaTela();
        jLabelStatusFinalizado.setText("");        
    }
    
    public void ResultadoPedido() {   
        connFinalizacao.conexao();
        connFinalizacao.executaSQL("select pedido.cod_cliente AS id,pedido.cod_pedido,clientes.nome_cliente,pedido.valor_total,pedido.status,pedido.desconto,(SELECT SUM(pedido.valor_pago) - (SUM(pedido.valor_total) - SUM(pedido.desconto)) FROM pedido WHERE pedido.cod_cliente = id AND pedido.status = 'Finalizado') AS SALDO  from pedido,clientes where pedido.cod_cliente = clientes.id_cliente and pedido.cod_pedido = " + jTextFieldCodigo.getText() + "");
        try {
            if (!connFinalizacao.rs.next()) {
                LimpaTela();
                JOptionPane.showMessageDialog(this, "Pedido não encontrado!");                
            } else {
                connFinalizacao.rs.first();
                jLabelCodigo.setText(String.valueOf(connFinalizacao.rs.getInt("cod_pedido")));                
                jLabelNome.setText(connFinalizacao.rs.getString("nome_cliente")); 
                jLabelValor.setText(String.valueOf(formatoMoeda.format(connFinalizacao.rs.getDouble("valor_total"))));
                jLabelStatus.setText(connFinalizacao.rs.getString("status")); 
                mod.setCod_pedido(connFinalizacao.rs.getInt("cod_pedido")); 
                mod.setValor_pago(connFinalizacao.rs.getBigDecimal("valor_total").subtract(connFinalizacao.rs.getBigDecimal("desconto")));
                saldo = connFinalizacao.rs.getDouble("SALDO");
            }
        } catch (SQLException ex) {            
        }
        connFinalizacao.desconecta();
    }
    
    public void FinalizaPedido() {                
        mod.setStatus("Finalizado");
        control.AlterarStatus(mod);
        control.FinalizaValorPago(mod);    
        jTextFieldCodigo.setText("");       
    }
    
    public void LimpaTela() {
        jTextFieldCodigo.setText("");
        jLabelCodigo.setText("");
        jLabelNome.setText("");
        jLabelStatus.setText("");        
        jLabelValor.setText("");
        jTextFieldCodigo.setText("");        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabelCodigo = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelValor = new javax.swing.JLabel();
        jLabelStatus = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelStatusFinalizado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Finalização de Pedidos");

        jLabel1.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jLabel1.setText("Código:");

        jTextFieldCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCodigoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCodigoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCodigoKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Bremen Bd BT", 0, 10)); // NOI18N
        jLabel2.setText("[ENTER]");

        jLabelCodigo.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N

        jLabelNome.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N

        jLabelValor.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N

        jLabelStatus.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Bremen Bd BT", 0, 10)); // NOI18N
        jLabel3.setText("Código:");

        jLabel4.setFont(new java.awt.Font("Bremen Bd BT", 0, 10)); // NOI18N
        jLabel4.setText("Nome:");

        jLabel5.setFont(new java.awt.Font("Bremen Bd BT", 0, 10)); // NOI18N
        jLabel5.setText("Total:");

        jLabel6.setFont(new java.awt.Font("Bremen Bd BT", 0, 10)); // NOI18N
        jLabel6.setText("Status:");

        jLabelStatusFinalizado.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jLabelStatusFinalizado.setForeground(new java.awt.Color(0, 153, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelValor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelStatusFinalizado, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelValor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelStatusFinalizado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(490, 234));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodigoKeyReleased
       
           
    }//GEN-LAST:event_jTextFieldCodigoKeyReleased

    private void jTextFieldCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodigoKeyTyped
        if(!caracteresNum.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCodigoKeyTyped

    private void jTextFieldCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodigoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(!"".equals(jTextFieldCodigo.getText())) {
                jLabelStatusFinalizado.setText("");
                ResultadoPedido();
            }
            if (saldo == 0) {
                if ("Em Preparo".equals(jLabelStatus.getText()) || "Enviado".equals(jLabelStatus.getText())) {  
                    jLabelStatusFinalizado.setText("Pedido "+ mod.getCod_pedido() +" Finalizado");
                    FinalizaPedido();
                } else {
                    JOptionPane.showMessageDialog(this, "Não é possível finalizar este pedido! Status: " + jLabelStatus.getText());
                }            
            } else {                
                JOptionPane.showMessageDialog(this, "Este pedido possui saldo em haver/devedor. Será necessário finalizar manualmente!");
                LimpaTela();
            }
        }
    }//GEN-LAST:event_jTextFieldCodigoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFinalizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFinalizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFinalizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFinalizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmFinalizacao().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelStatusFinalizado;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCodigo;
    // End of variables declaration//GEN-END:variables
}
