/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ConectaBanco;
import controle.ControleProdutos;
import controle.ModeloTabela;
import java.math.BigDecimal;
import java.sql.Date;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modelo.ModeloProdutos;

/**
 *
 * @author Thiago
 */
public class FrmProdutos extends javax.swing.JFrame {

    ConectaBanco connProdutos = new ConectaBanco();
    ModeloProdutos mod = new ModeloProdutos();        
    ControleProdutos control = new ControleProdutos();
    FrmAddFornecedor frmF = new FrmAddFornecedor();
    private int btnLista;      
    
    
    /**
     * Creates new form FrmProdutos
     */
    public FrmProdutos() {
        initComponents();
        jTabbedPane1.setEnabledAt(3, false);
        connProdutos.conexao();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jComboBoxUn = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCaixa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldPrecoV = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabelMarkup = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelPreco = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldGTIN = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldGTINE = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldEstoqueMi = new javax.swing.JTextField();
        jTextFieldEstoqueMa = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFornecedor = new javax.swing.JTable();
        jButtonInserirF = new javax.swing.JButton();
        jButtonAlterarF = new javax.swing.JButton();
        jButtonExcluirF = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableItens = new javax.swing.JTable();
        jButtonInserirP = new javax.swing.JButton();
        jButtonAlterarP = new javax.swing.JButton();
        jButtonExcluirP = new javax.swing.JButton();
        jButtonGravar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Produtos");

        jLabel1.setFont(new java.awt.Font("Bremen Bd BT", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Cadastro de Produtos");

        jLabel3.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jLabel3.setText("Nome:");

        jTabbedPane1.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jLabel2.setText("Código:");

        jTextFieldCodigo.setEnabled(false);

        jComboBoxUn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UN", "CX", "GR", "KG", "LT", "MC", "ML" }));

        jLabel5.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jLabel5.setText("Qtde. por caixa:");

        jLabel6.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jLabel6.setText("Preço Venda:");

        jLabel7.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Markup:");

        jLabelMarkup.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelMarkup.setForeground(new java.awt.Color(255, 0, 0));
        jLabelMarkup.setText("0,00");

        jLabel9.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Preço Sugerido:");

        jLabelPreco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelPreco.setForeground(new java.awt.Color(255, 0, 0));
        jLabelPreco.setText("0,00");

        jLabel11.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jLabel11.setText("GTIN:");

        jLabel12.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jLabel12.setText("GTIN/Embalagem:");

        jLabel13.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jLabel13.setText("Categoria:");

        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alimentos", "Bebidas", "Doces", "Marmita", "Porções", "Refeição" }));
        jComboBoxCategoria.setSelectedIndex(-1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jComboBoxUn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPrecoV, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabelMarkup))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabelPreco))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldGTIN, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldGTINE, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxUn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jTextFieldCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldPrecoV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldGTIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jTextFieldGTINE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabelMarkup)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabelPreco))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dados Gerais", jPanel2);

        jLabel8.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jLabel8.setText("Mínimo:");

        jLabel10.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jLabel10.setText("Máximo:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEstoqueMa))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldEstoqueMi, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(385, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldEstoqueMi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldEstoqueMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Estoque", jPanel3);

        jTableFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableFornecedor);

        jButtonInserirF.setFont(new java.awt.Font("Bremen Bd BT", 0, 10)); // NOI18N
        jButtonInserirF.setText("Inserir");
        jButtonInserirF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirFActionPerformed(evt);
            }
        });

        jButtonAlterarF.setFont(new java.awt.Font("Bremen Bd BT", 0, 10)); // NOI18N
        jButtonAlterarF.setText("Alterar");
        jButtonAlterarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarFActionPerformed(evt);
            }
        });

        jButtonExcluirF.setFont(new java.awt.Font("Bremen Bd BT", 0, 10)); // NOI18N
        jButtonExcluirF.setText("Excluir");
        jButtonExcluirF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButtonInserirF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAlterarF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluirF)))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInserirF)
                    .addComponent(jButtonAlterarF)
                    .addComponent(jButtonExcluirF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jTabbedPane1.addTab("Fornecedor", jPanel4);

        jTableItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableItens);

        jButtonInserirP.setFont(new java.awt.Font("Bremen Bd BT", 0, 10)); // NOI18N
        jButtonInserirP.setText("Inserir");

        jButtonAlterarP.setFont(new java.awt.Font("Bremen Bd BT", 0, 10)); // NOI18N
        jButtonAlterarP.setText("Alterar");

        jButtonExcluirP.setFont(new java.awt.Font("Bremen Bd BT", 0, 10)); // NOI18N
        jButtonExcluirP.setText("Excluir");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButtonInserirP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAlterarP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluirP)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInserirP)
                    .addComponent(jButtonAlterarP)
                    .addComponent(jButtonExcluirP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Itens", jPanel5);

        jButtonGravar.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jButtonGravar.setText("Gravar");
        jButtonGravar.setMaximumSize(new java.awt.Dimension(80, 23));
        jButtonGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarActionPerformed(evt);
            }
        });

        jButtonLimpar.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.setMaximumSize(new java.awt.Dimension(90, 23));
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonSair.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.setMaximumSize(new java.awt.Dimension(80, 23));
        jButtonSair.setMinimumSize(new java.awt.Dimension(80, 23));
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNome))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonGravar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGravar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        LimpaTela();        
        mod.setBtnAlterarLista(1);        
        dispose();        
    }//GEN-LAST:event_jButtonSairActionPerformed

    public void ReceberBotao(ModeloProdutos btn){              
        btnLista = btn.getBtnAlterarLista();        
        if (btnLista == 1) {
            LimpaTela();
            connProdutos.executaSQL("select max(id_produto) from produtos");
            try {
                connProdutos.rs.first();
                int id = connProdutos.rs.getInt("max(id_produto)");                
                jTextFieldCodigo.setText(String.valueOf(id+1));                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro " + ex);
            }            
        }         
                
        if (btnLista == 2){ 
            jTextFieldCodigo.setText(String.valueOf(btn.getId_produto()));
            jTextFieldCaixa.setText(String.valueOf(btn.getQtda_caixa()));
            jTextFieldEstoqueMa.setText(String.valueOf(btn.getEstoquema()));
            jTextFieldEstoqueMi.setText(String.valueOf(btn.getEstoquemi()));
            jTextFieldGTIN.setText(btn.getGtin_produto());
            jTextFieldGTINE.setText(btn.getGtin_embalagem());
            jTextFieldNome.setText(btn.getNome_produto());
            String preco_venda = String.valueOf(btn.getPreco_venda());
            jTextFieldPrecoV.setText(preco_venda.replace('.',','));            
            jComboBoxUn.setSelectedItem(btn.getUnidade_produto());
            jComboBoxCategoria.setSelectedItem(btn.getCategoria());            
            preencherTabelaFornecedor("select fornecedor.id_fornecedor,fornecedor.fantasia_fornecedor,produto_fornecedor.preco_custo,produto_fornecedor.data from fornecedor,produto_fornecedor where produto_fornecedor.cod_produto="+ btn.getId_produto() +" and fornecedor.id_fornecedor=produto_fornecedor.cod_fornecedor");
            preencherTabelaItens("select itens_produtos.cod_item, produtos.nome_produto,itens_produtos.qtda_item, produto_fornecedor.preco_custo, produtos.qtda_caixa, produto_fornecedor.data from itens_produtos,produtos,produto_fornecedor where produtos.id_produto = itens_produtos.cod_item and produtos.id_produto = produto_fornecedor.cod_produto and itens_produtos.cod_produto =" + btn.getId_produto() +" and produto_fornecedor.data = (select max(data) from produto_fornecedor where cod_produto = itens_produtos.cod_item ) group by itens_produtos.cod_item");
            
        }
    }           
    
    public void preencherTabelaFornecedor(String SQL){
        ArrayList dados = new ArrayList();    
        String [] Colunas = new String[]{"Fantasia","Preço Custo","Data Compra"};
           
               
        connProdutos.executaSQL(SQL);
        try {
            if (!connProdutos.rs.next()){
                
            } else {     
                    connProdutos.rs.first();
                        do{
                            Date dataFormat = connProdutos.rs.getDate("data");
                            String data = new SimpleDateFormat("dd/MM/yyyy").format(dataFormat); 
                            String preco_custo = String.valueOf(connProdutos.rs.getDouble("preco_custo"));                            
                           dados.add(new Object[]{connProdutos.rs.getString("fantasia_fornecedor"),preco_custo.replace('.', ','),data});
                        }while(connProdutos.rs.next());         
                    
               }   
        } catch (SQLException ex) {
                
        }  
        
        ModeloTabela modelo = new ModeloTabela(dados, Colunas); 
        jTableFornecedor.setModel(modelo);
        jTableFornecedor.getColumnModel().getColumn(0).setPreferredWidth(110);
        jTableFornecedor.getColumnModel().getColumn(0).setResizable(true);
        jTableFornecedor.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTableFornecedor.getColumnModel().getColumn(1).setResizable(true);
        jTableFornecedor.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableFornecedor.getColumnModel().getColumn(2).setResizable(true);        
        jTableFornecedor.getTableHeader().setReorderingAllowed(false);
        jTableFornecedor.setAutoResizeMode(jTableFornecedor.AUTO_RESIZE_OFF);
        jTableFornecedor.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); 
        
        
    }
    
    public void preencherTabelaItens(String SQL){
        ArrayList dados = new ArrayList();
        Double custoUn;
        Double precoUn;
        BigDecimal valorArred;
     
        String [] Colunas = new String[]{"Produto","Quantidade","Custo Unitário"};                                
          
        connProdutos.executaSQL(SQL);
        try {
            if (!connProdutos.rs.next()){
                
            } else {                      
                          
                    connProdutos.rs.first();
                        do{
                            custoUn = connProdutos.rs.getDouble("preco_custo") / connProdutos.rs.getDouble("qtda_caixa");
                            precoUn = custoUn * connProdutos.rs.getDouble("qtda_item");                            
                            valorArred = control.ArredondaValor(precoUn);
                           dados.add(new Object[]{connProdutos.rs.getString("nome_produto"),connProdutos.rs.getDouble("qtda_item"),valorArred});
                        }while(connProdutos.rs.next());         
                    
                }   
        } catch (SQLException ex) {
                
        }
            
        
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTableItens.setModel(modelo);
        jTableItens.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTableItens.getColumnModel().getColumn(0).setResizable(true);
        jTableItens.getColumnModel().getColumn(1).setPreferredWidth(50);
        jTableItens.getColumnModel().getColumn(1).setResizable(true);    
        jTableItens.getColumnModel().getColumn(2).setPreferredWidth(50);
        jTableItens.getColumnModel().getColumn(2).setResizable(true);    
        jTableItens.getTableHeader().setReorderingAllowed(false);
        jTableItens.setAutoResizeMode(jTableItens.AUTO_RESIZE_OFF);
        jTableItens.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
                
    }  
    
    private void LimpaTela(){
        
        jTextFieldCaixa.setText("");        
        jTextFieldEstoqueMa.setText("");
        jTextFieldEstoqueMi.setText("");
        jTextFieldGTIN.setText("");
        jTextFieldGTINE.setText("");
        jTextFieldNome.setText("");
        jTextFieldPrecoV.setText("");
        jComboBoxCategoria.setSelectedItem(0);
        jComboBoxUn.setSelectedItem(0);
        
        ArrayList dados = new ArrayList();
        String [] Colunas = new String[]{};
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTableFornecedor.setModel(modelo);   
        
        connProdutos.executaSQL("select max(id_produto) from produtos");
            try {
                connProdutos.rs.first();
                int id = connProdutos.rs.getInt("max(id_produto)");                
                jTextFieldCodigo.setText(String.valueOf(id+1));                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro " + ex);
            }            
        
    }
    
    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        LimpaTela();        
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonInserirFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirFActionPerformed
        mod.setBtnAlterar(1); 
        mod.setId_produto(Integer.parseInt(jTextFieldCodigo.getText()));     
        frmF.ReceberDados(mod);
        frmF.atulizaForn(this);
    }//GEN-LAST:event_jButtonInserirFActionPerformed

  
    
    private void jButtonAlterarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarFActionPerformed
       connProdutos.conexao();       
       String nome = ""+jTableFornecedor.getValueAt(jTableFornecedor.getSelectedRow(),0); 
       Integer cod = Integer.parseInt(jTextFieldCodigo.getText()); 
       mod.setId_produto(Integer.parseInt(jTextFieldCodigo.getText())); 
       connProdutos.executaSQL("select fornecedor.id_fornecedor,fornecedor.fantasia_fornecedor,produto_fornecedor.preco_custo,produto_fornecedor.data,produto_fornecedor.cod_produto from fornecedor,produto_fornecedor where produto_fornecedor.cod_fornecedor = fornecedor.id_fornecedor and fornecedor.fantasia_fornecedor='"+nome+"' and produto_fornecedor.cod_produto='"+cod+"'");             
     
       try { 
            connProdutos.rs.first();                                              
            mod.setData(connProdutos.rs.getString("data"));            
            mod.setCod_fornecedor(connProdutos.rs.getInt("id_fornecedor"));
            mod.setCod_produto(connProdutos.rs.getInt("cod_produto"));
            mod.setPreco_custo(connProdutos.rs.getDouble("preco_custo"));
            mod.setFantasia_fornecedor(connProdutos.rs.getString("fantasia_fornecedor"));            
            mod.setBtnAlterar(2);
            frmF.ReceberDados(mod);            
            frmF.atulizaForn(this);                        
                
        } catch (SQLException s){
            JOptionPane.showMessageDialog(rootPane,"Erro ao selecionar os dados!\nErro: " + s);        
        }
    }//GEN-LAST:event_jButtonAlterarFActionPerformed

    private void jButtonGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarActionPerformed
        mod.setId_produto(Integer.parseInt(jTextFieldCodigo.getText()));
        mod.setNome_produto(jTextFieldNome.getText());
        mod.setGtin_produto(jTextFieldGTIN.getText());
        mod.setGtin_embalagem(jTextFieldGTINE.getText());
        if (!"".equals(jTextFieldEstoqueMa.getText())){
            mod.setEstoquema(Integer.parseInt(jTextFieldEstoqueMa.getText()));
        }
        if (!"".equals(jTextFieldEstoqueMi.getText())){
            mod.setEstoquemi(Integer.parseInt(jTextFieldEstoqueMi.getText()));
        }        
        
        mod.setUnidade_produto((String) jComboBoxUn.getSelectedItem());            
        mod.setQtda_caixa(Double.parseDouble(jTextFieldCaixa.getText()));            
        mod.setPreco_venda(Double.parseDouble(jTextFieldPrecoV.getText().replace(',','.')));
        mod.setCategoria((String) jComboBoxCategoria.getSelectedItem());             
        
        if(btnLista == 1){            
            control.InserirProdutos(mod);            
        }
        if(btnLista == 2){
            control.AlterarProdutos(mod);
            dispose();
        }         
        LimpaTela();  
        ExecutaAttListaProd();
    }//GEN-LAST:event_jButtonGravarActionPerformed

    private void jButtonExcluirFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirFActionPerformed
        String nome = ""+jTableFornecedor.getValueAt(jTableFornecedor.getSelectedRow(),0); 
        mod.setId_produto(Integer.parseInt(jTextFieldCodigo.getText())); 
        mod.setFantasia_fornecedor(nome);
        control.ExcluirProForn(mod);
        preencherTabelaFornecedor("select fornecedor.id_fornecedor,fornecedor.fantasia_fornecedor,produto_fornecedor.preco_custo,produto_fornecedor.data from fornecedor,produto_fornecedor where produto_fornecedor.cod_produto="+ mod.getId_produto() +" and fornecedor.id_fornecedor=produto_fornecedor.cod_fornecedor");
    }//GEN-LAST:event_jButtonExcluirFActionPerformed

    public void ExecutaAttForn() {
        mod.setId_produto(Integer.parseInt(jTextFieldCodigo.getText()));
        preencherTabelaFornecedor("select fornecedor.id_fornecedor,fornecedor.fantasia_fornecedor,produto_fornecedor.preco_custo,produto_fornecedor.data from fornecedor,produto_fornecedor where produto_fornecedor.cod_produto="+ mod.getId_produto() +" and fornecedor.id_fornecedor=produto_fornecedor.cod_fornecedor");
        
    }    
    
    private FrmListaProduto frmListaProd;
    
    public void atulizaListaProd (FrmListaProduto attListaProd) {
        this.frmListaProd = attListaProd;
        setVisible(true);
    }
    
    public void ExecutaAttListaProd() {
        frmListaProd.ExecutaAttListaProduto();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterarF;
    private javax.swing.JButton jButtonAlterarP;
    private javax.swing.JButton jButtonExcluirF;
    private javax.swing.JButton jButtonExcluirP;
    private javax.swing.JButton jButtonGravar;
    private javax.swing.JButton jButtonInserirF;
    private javax.swing.JButton jButtonInserirP;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JComboBox<String> jComboBoxUn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMarkup;
    private javax.swing.JLabel jLabelPreco;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableFornecedor;
    private javax.swing.JTable jTableItens;
    private javax.swing.JTextField jTextFieldCaixa;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldEstoqueMa;
    private javax.swing.JTextField jTextFieldEstoqueMi;
    private javax.swing.JTextField jTextFieldGTIN;
    private javax.swing.JTextField jTextFieldGTINE;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPrecoV;
    // End of variables declaration//GEN-END:variables
}
