/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import static antlr.ANTLRTokenTypes.ESC;
import controle.Impressao;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import static sun.jvm.hotspot.debugger.x86.X86ThreadContext.GS;



/**
 *
 * @author thiag
 */
public class FrmPedidoAntigo extends javax.swing.JFrame {
    
    Impressao impressao = new Impressao();
    String data = "dd/MM/yyyy";
    String hora = "HH:mm:ss";
    String data1, hora1;    
    
public static final char[] START = new char[] { 0x1B, '@' };
public static final char[] CORTAR = new char[] { 0x1B, 'm' };
private static final byte[] CHAR_SIZE_0 = { 0x1B, 0x21, 0x00 };
private static final byte[] CHAR_SIZE_1 = { 0x1B, 0x21, 0x01 };
private static final byte[] CHAR_SIZE_2 = { 0x1B, 0x21, 0x30 };
private static final byte[] CHAR_SIZE_3 = { 0x1B, 0x21, 0x31 }; 
private static final byte[] AVANCA = { 0x19 };
private static final byte[] POSESQUEDA = { 0x1B, 'j', '0' };
private static final byte[] POSCENTRO = { 0x1B, 'j', '1' };
private static final byte[] POSDIREITA = { 0x1B, 'j', '2' };
private static final byte[] TABHORIZONTAL = { 0x09 };
private static final byte[] startTextCondensado = {0x1B, 0x0F };
private static final byte[] endTextCondensado = { 0x12 };
private static final byte[] startTextExpandido = { 0x1B, 'W', '1' };
private static final byte[] endtTextExpandido = { 0x1B, 'W', '0' };
private static final char[] QRCODE_PREFIX = new char[] { 0x1B, 0x81 };  
private static final char[] ESPACOHORIZONTAL = new char[] { 0x20 }; 
private static final byte[] SET_LINE_SPACING_24 =   { 0x1B, 0x33, (byte) 24 };
private static final byte[] SET_LINE_SPACING_30 =   { 0x1B, 0x33, (byte) 30 };  
private static final byte[] PRINT_AND_FEED_PAPER =  { 0x1B, 0x4A, 0x00 };   
private static final byte[] REVERSAO =  { 0x10, 0x4D, 0x01 };
private static final String ATIVA_NEGRITO = ESC + "E";
private static final String DESATIVA_NEGRITO = ESC + "F"; 
private static final String ATIVA_ITALICO = ESC + "4";
private static final String DESATIVA_ITALICO = ESC + "5";
private static final String BARCODE = GS + "k";


   


    /**
     * Creates new form FrmPedido
     */
    public FrmPedidoAntigo() {
        initComponents();         	       
        jTextAreaPedido.setLineWrap(true);        
        LimpaTela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaPedido = new javax.swing.JTextArea();
        jButtonImprimir = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaEndereco = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaObs = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pedidos");
        setAlwaysOnTop(true);

        jTextAreaPedido.setColumns(20);
        jTextAreaPedido.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextAreaPedido.setRows(5);
        jTextAreaPedido.setNextFocusableComponent(jTextAreaEndereco);
        jTextAreaPedido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextAreaPedidoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTextAreaPedido);

        jButtonImprimir.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jButtonImprimir.setText("Imprimir");
        jButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirActionPerformed(evt);
            }
        });

        jButtonLimpar.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonSair.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bremen Bd BT", 0, 14)); // NOI18N
        jLabel1.setText("Pedido:");

        jLabel2.setFont(new java.awt.Font("Bremen Bd BT", 0, 14)); // NOI18N
        jLabel2.setText("ENDEREÇO:");

        jTextAreaEndereco.setColumns(20);
        jTextAreaEndereco.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextAreaEndereco.setRows(5);
        jTextAreaEndereco.setNextFocusableComponent(jTextAreaObs);
        jTextAreaEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextAreaEnderecoKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTextAreaEndereco);

        jLabel3.setFont(new java.awt.Font("Bremen Bd BT", 0, 14)); // NOI18N
        jLabel3.setText("OBSERVAÇÃO:");

        jTextAreaObs.setColumns(20);
        jTextAreaObs.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextAreaObs.setRows(5);
        jTextAreaObs.setNextFocusableComponent(jButtonImprimir);
        jTextAreaObs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextAreaObsKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTextAreaObs);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButtonImprimir)
                        .addGap(70, 70, 70)
                        .addComponent(jButtonLimpar)
                        .addGap(80, 80, 80)
                        .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonImprimir)
                    .addComponent(jButtonLimpar)
                    .addComponent(jButtonSair))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirActionPerformed
        impressao.detectaImpressoras();
        java.util.Date agora = new java.util.Date();
	SimpleDateFormat formata = new SimpleDateFormat(data);
	data1 = formata.format(agora);
	formata = new SimpleDateFormat(hora);
	hora1 = formata.format(agora);         
       /* impressao.imprime(data1 +" - "+ hora1 +"\n\r\n\r"
                + "PEDIDO:\n\r"
                + "----------------------------------------\n\r\n\r"
                + jTextAreaPedido.getText() +"\n\r"
                + "----------------------------------------\n\r\n\r"
                + "ENDERECO:\n\r"
                + "----------------------------------------\n\r\n\r"
                + jTextAreaEndereco.getText() +"\n\r"
                + "----------------------------------------\n\r\n\r"
                + "OBSERVACAO:\n\r"
                + "----------------------------------------\n\r\n\r"
                + jTextAreaObs.getText() +"\n\r\n\r\n\r\n\r\n\r");
                 */                  
       String texto = new String (START) +
                      ATIVA_NEGRITO +"texto negrito" + DESATIVA_NEGRITO;
       String texto1 = START + ATIVA_ITALICO + "\ntexto italico" + DESATIVA_ITALICO;
       String texto2 =  CHAR_SIZE_0 + "\ntexto char 0";
       String texto3 = CHAR_SIZE_1 + "\ntexto char 1";
       String texto4 = CHAR_SIZE_2 + "\ntexto char 2";
       String texto5 = CHAR_SIZE_3 + "\ntexto char 3";
       
       impressao.imprime(texto);
       impressao.imprime(texto1);
       impressao.imprime(texto2);
       impressao.imprime(texto3);
       impressao.imprime(texto4);
       impressao.imprime(texto5);
        
        impressao.acionarGuilhotina(); 
        LimpaTela();
    }//GEN-LAST:event_jButtonImprimirActionPerformed

    private void LimpaTela() {
        jTextAreaPedido.setText("");
        jTextAreaEndereco.setText("");
        jTextAreaObs.setText("");        
    }
    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
       LimpaTela();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jTextAreaPedidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaPedidoKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_TAB){
            jTextAreaEndereco.requestFocus();            
}
        
    }//GEN-LAST:event_jTextAreaPedidoKeyPressed

    private void jTextAreaEnderecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaEnderecoKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_TAB){
            jTextAreaObs.requestFocus();           

}
    }//GEN-LAST:event_jTextAreaEnderecoKeyPressed

    private void jTextAreaObsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaObsKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_TAB){
             jButtonImprimir.requestFocus();
}
    }//GEN-LAST:event_jTextAreaObsKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPedidoAntigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPedidoAntigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPedidoAntigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPedidoAntigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmPedidoAntigo().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaEndereco;
    private javax.swing.JTextArea jTextAreaObs;
    private javax.swing.JTextArea jTextAreaPedido;
    // End of variables declaration//GEN-END:variables

    private void ControleImpressao() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
