/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ConectaBanco;
import java.io.InputStream;
import java.net.URL;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author thiag
 */
public class FrmRelFinanceiroCliente extends javax.swing.JFrame {
    ConectaBanco conecta = new ConectaBanco();
    DefaultListModel MODELO;
    String [] codigoC, codigoP;
    int codCliente;
    String caracteresNum = "0987654321";
    
    /**
     * Creates new form FrmBalanco
     */
    public FrmRelFinanceiroCliente() {
        initComponents();
        conecta.conexao();
        
        jComboBoxStatus.setSelectedItem("Finalizado");   
        jDateChooserDe.setDate(new Date());
        jDateChooserAte.setDate(new Date());  
        MODELO = new DefaultListModel();
        jListCliente.setVisible(false);
        jListCliente.setModel(MODELO);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldCliente = new javax.swing.JTextField();
        jListCliente = new javax.swing.JList<>();
        jComboBoxStatus = new javax.swing.JComboBox<>();
        jDateChooserDe = new com.toedter.calendar.JDateChooser();
        jDateChooserAte = new com.toedter.calendar.JDateChooser();
        jButtonGerar = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório Financeiro");

        jPanel1.setLayout(null);

        jTextFieldCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldClienteKeyReleased(evt);
            }
        });
        jPanel1.add(jTextFieldCliente);
        jTextFieldCliente.setBounds(80, 30, 137, 19);

        jListCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jListCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jListClienteMousePressed(evt);
            }
        });
        jPanel1.add(jListCliente);
        jListCliente.setBounds(80, 50, 137, 90);

        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agendado", "Em Preparo", "Enviado", "Finalizado", "Cancelado" }));
        jPanel1.add(jComboBoxStatus);
        jComboBoxStatus.setBounds(72, 71, 137, 19);

        jDateChooserDe.setDateFormatString("dd/MM/y");
        jPanel1.add(jDateChooserDe);
        jDateChooserDe.setBounds(40, 150, 110, 19);

        jDateChooserAte.setDateFormatString("dd/MM/y");
        jPanel1.add(jDateChooserAte);
        jDateChooserAte.setBounds(190, 150, 110, 19);

        jButtonGerar.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jButtonGerar.setText("Gerar");
        jButtonGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGerar);
        jButtonGerar.setBounds(37, 186, 100, 23);

        jButtonFechar.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jButtonFechar.setText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonFechar);
        jButtonFechar.setBounds(176, 186, 100, 23);

        jLabel1.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jLabel1.setText("Status:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(21, 75, 46, 15);

        jLabel2.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jLabel2.setText("Período");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(12, 118, 70, 15);

        jLabel3.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jLabel3.setText("De:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(12, 153, 30, 15);

        jLabel4.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jLabel4.setText("Até:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(160, 150, 26, 15);

        jLabel5.setFont(new java.awt.Font("Bremen Bd BT", 0, 12)); // NOI18N
        jLabel5.setText("Cliente:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(21, 35, 60, 15);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );

        setSize(new java.awt.Dimension(404, 286));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        dispose();
        conecta.desconecta();
    }//GEN-LAST:event_jButtonFecharActionPerformed

    public void ListaCliente() {        
        try {            
            conecta.executaSQL("select * from clientes where nome_cliente like '" + jTextFieldCliente.getText() + "%' order by nome_cliente");
            MODELO.removeAllElements();
            int v = 0; 
            codigoC = new String[4];
            while (conecta.rs.next() & v < 4) {
                MODELO.addElement(conecta.rs.getString("nome_cliente"));
                codigoC[v] = conecta.rs.getString("id_cliente");
                v++;
            }
            if (v >=1) {
                jListCliente.setVisible(true);                             
            } else {
                jListCliente.setVisible(false);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao listar dados");
            
        }
        
    }
    
    public void MostraCliente() {
        int Linha = jListCliente.getSelectedIndex();
        if (Linha >= 0) {
            conecta.executaSQL("select * from clientes where id_cliente = " + codigoC[Linha] + "");
            ResultadoCliente();
        }
    }
    
    public void ResultadoCliente() {                             
        try {
            conecta.rs.first();            
            codCliente = conecta.rs.getInt("id_cliente");
            jTextFieldCliente.setText(conecta.rs.getString("nome_cliente"));            
        } catch (SQLException ex) {
            
        }
    }
    
    private void jButtonGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarActionPerformed
        try { 
            Map parameters = new HashMap();                        
            URL arquivo = getClass().getResource( "/relatorios/RelatorioFinanceiroCliente.jasper" );	    
	    JasperReport jasperReport = (JasperReport) JRLoader.loadObject( arquivo );
            String dataDe = new SimpleDateFormat("yyyy-MM-dd").format(jDateChooserDe.getDate()); 
            String dataAte = new SimpleDateFormat("yyyy-MM-dd").format(jDateChooserAte.getDate());
            String dt1 = new SimpleDateFormat("dd/MM/yyyy").format(jDateChooserDe.getDate()); 
            String dt2 = new SimpleDateFormat("dd/MM/yyyy").format(jDateChooserAte.getDate());            
            parameters.put("dt1", dt1);
            parameters.put("dt2", dt2); 
            parameters.put("codCliente", codCliente);
            InputStream logo = this.getClass().getResourceAsStream("/imagens/logonovo.png");
            parameters.put("logo", logo);
            String Status = (String) jComboBoxStatus.getSelectedItem();            
            parameters.put("Status", Status); 
            conecta.executaSQL("SELECT pedido.data_agendada,clientes.nome_cliente,produtos.nome_produto,\n" +
                               "itens_pedido.qtda_produto, itens_pedido.valor_un,(SELECT SUM(valor_pago) from pedido where cod_cliente = '"+ codCliente +"' AND data_agendada BETWEEN '"+ dataDe +"' AND '"+ dataAte +"') AS ValorPago, (SELECT SUM(desconto) from pedido where cod_cliente = '"+ codCliente +"' AND data_agendada BETWEEN '"+ dataDe +"' AND '"+ dataAte +"') AS Desconto\n" +                                       
                               "FROM produtos,itens_pedido,pedido,clientes\n" +
                               "WHERE pedido.data_agendada BETWEEN '"+ dataDe +"' AND '"+ dataAte +"' \n" +
                               "AND pedido.cod_pedido = itens_pedido.cod_pedido\n" +
                               "AND clientes.id_cliente = pedido.cod_cliente \n" +
                               "AND produtos.id_produto = itens_pedido.cod_produto \n" +                                       
                               "AND pedido.status = '"+ Status +"' \n" +
                               "AND pedido.cod_cliente = '"+ codCliente +"'\n" +
                               "ORDER BY pedido.data_agendada,produtos.nome_produto");
                if (conecta.rs.isBeforeFirst() != false ) {
                    JRResultSetDataSource relatResul = new JRResultSetDataSource(conecta.rs);
                    JasperPrint jpPrint = JasperFillManager.fillReport(jasperReport, parameters, relatResul);
                    JasperViewer jv = new JasperViewer(jpPrint,false);
                    jv.setVisible(true);
                    jv.toFront();
                    dispose();                
                } else {
                    JOptionPane.showMessageDialog(this,"Período sem registros!");
                }
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao chamar o relatório!\nErro: "+ ex);        
        } catch (SQLException ex) {
            Logger.getLogger(FrmRelFinanceiroCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonGerarActionPerformed

    private void jTextFieldClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldClienteKeyReleased
      /*  if (caracteresNum.contains(evt.getKeyChar()+"")) { 
            conecta.executaSQL("select * from clientes where id_cliente = " + jTextFieldCliente.getText() + "");
            ResultadoCliente();
            jListCliente.setVisible(false);            
        } */
      ListaCliente();
    }//GEN-LAST:event_jTextFieldClienteKeyReleased

    private void jListClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListClienteMousePressed
        MostraCliente();
        jListCliente.setVisible(false);        
    }//GEN-LAST:event_jListClienteMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRelFinanceiroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRelFinanceiroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRelFinanceiroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRelFinanceiroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRelFinanceiroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonGerar;
    private javax.swing.JComboBox<String> jComboBoxStatus;
    private com.toedter.calendar.JDateChooser jDateChooserAte;
    private com.toedter.calendar.JDateChooser jDateChooserDe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jListCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCliente;
    // End of variables declaration//GEN-END:variables
}
